// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: iotMessage.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from iotMessage.proto</summary>
public static partial class IotMessageReflection {

  #region Descriptor
  /// <summary>File descriptor for iotMessage.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static IotMessageReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "ChBpb3RNZXNzYWdlLnByb3RvIkQKB1JlcXVlc3QSEwoLUmVxdWVzdFR5cGUY",
          "ASABKAkSGwoEbGlzdBgCIAEoCzIILklvdFVuaXRIAIgBAUIHCgVfbGlzdCIl",
          "CgtJb3RVbml0TGlzdBIWCgRsaXN0GAEgAygLMgguSW90VW5pdCKJAQoHSW90",
          "VW5pdBIQCghEZXZpY2VJRBgBIAEoCRIQCghJUGFkcmVzcxgCIAEoCRIRCglU",
          "aW1lc3RhbXAYAyABKAMSEgoKRGV2aWNlVHlwZRgEIAEoCRIWCg5EZXZpY2VD",
          "YXRlZ29yeRgFIAEoCRINCgVWYWx1ZRgGIAEoARIMCgRVbml0GAcgASgJYgZw",
          "cm90bzM="));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { },
        new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::Request), global::Request.Parser, new[]{ "RequestType", "List" }, new[]{ "List" }, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::IotUnitList), global::IotUnitList.Parser, new[]{ "List" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::IotUnit), global::IotUnit.Parser, new[]{ "DeviceID", "IPadress", "Timestamp", "DeviceType", "DeviceCategory", "Value", "Unit" }, null, null, null, null)
        }));
  }
  #endregion

}
#region Messages
public sealed partial class Request : pb::IMessage<Request>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<Request> _parser = new pb::MessageParser<Request>(() => new Request());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pb::MessageParser<Request> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::IotMessageReflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public Request() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public Request(Request other) : this() {
    requestType_ = other.requestType_;
    list_ = other.list_ != null ? other.list_.Clone() : null;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public Request Clone() {
    return new Request(this);
  }

  /// <summary>Field number for the "RequestType" field.</summary>
  public const int RequestTypeFieldNumber = 1;
  private string requestType_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string RequestType {
    get { return requestType_; }
    set {
      requestType_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "list" field.</summary>
  public const int ListFieldNumber = 2;
  private global::IotUnit list_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public global::IotUnit List {
    get { return list_; }
    set {
      list_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override bool Equals(object other) {
    return Equals(other as Request);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool Equals(Request other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (RequestType != other.RequestType) return false;
    if (!object.Equals(List, other.List)) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override int GetHashCode() {
    int hash = 1;
    if (RequestType.Length != 0) hash ^= RequestType.GetHashCode();
    if (list_ != null) hash ^= List.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (RequestType.Length != 0) {
      output.WriteRawTag(10);
      output.WriteString(RequestType);
    }
    if (list_ != null) {
      output.WriteRawTag(18);
      output.WriteMessage(List);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (RequestType.Length != 0) {
      output.WriteRawTag(10);
      output.WriteString(RequestType);
    }
    if (list_ != null) {
      output.WriteRawTag(18);
      output.WriteMessage(List);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int CalculateSize() {
    int size = 0;
    if (RequestType.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(RequestType);
    }
    if (list_ != null) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(List);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(Request other) {
    if (other == null) {
      return;
    }
    if (other.RequestType.Length != 0) {
      RequestType = other.RequestType;
    }
    if (other.list_ != null) {
      if (list_ == null) {
        List = new global::IotUnit();
      }
      List.MergeFrom(other.List);
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          RequestType = input.ReadString();
          break;
        }
        case 18: {
          if (list_ == null) {
            List = new global::IotUnit();
          }
          input.ReadMessage(List);
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 10: {
          RequestType = input.ReadString();
          break;
        }
        case 18: {
          if (list_ == null) {
            List = new global::IotUnit();
          }
          input.ReadMessage(List);
          break;
        }
      }
    }
  }
  #endif

}

public sealed partial class IotUnitList : pb::IMessage<IotUnitList>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<IotUnitList> _parser = new pb::MessageParser<IotUnitList>(() => new IotUnitList());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pb::MessageParser<IotUnitList> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::IotMessageReflection.Descriptor.MessageTypes[1]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public IotUnitList() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public IotUnitList(IotUnitList other) : this() {
    list_ = other.list_.Clone();
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public IotUnitList Clone() {
    return new IotUnitList(this);
  }

  /// <summary>Field number for the "list" field.</summary>
  public const int ListFieldNumber = 1;
  private static readonly pb::FieldCodec<global::IotUnit> _repeated_list_codec
      = pb::FieldCodec.ForMessage(10, global::IotUnit.Parser);
  private readonly pbc::RepeatedField<global::IotUnit> list_ = new pbc::RepeatedField<global::IotUnit>();
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public pbc::RepeatedField<global::IotUnit> List {
    get { return list_; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override bool Equals(object other) {
    return Equals(other as IotUnitList);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool Equals(IotUnitList other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if(!list_.Equals(other.list_)) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override int GetHashCode() {
    int hash = 1;
    hash ^= list_.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    list_.WriteTo(output, _repeated_list_codec);
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    list_.WriteTo(ref output, _repeated_list_codec);
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int CalculateSize() {
    int size = 0;
    size += list_.CalculateSize(_repeated_list_codec);
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(IotUnitList other) {
    if (other == null) {
      return;
    }
    list_.Add(other.list_);
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          list_.AddEntriesFrom(input, _repeated_list_codec);
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 10: {
          list_.AddEntriesFrom(ref input, _repeated_list_codec);
          break;
        }
      }
    }
  }
  #endif

}

public sealed partial class IotUnit : pb::IMessage<IotUnit>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<IotUnit> _parser = new pb::MessageParser<IotUnit>(() => new IotUnit());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pb::MessageParser<IotUnit> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::IotMessageReflection.Descriptor.MessageTypes[2]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public IotUnit() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public IotUnit(IotUnit other) : this() {
    deviceID_ = other.deviceID_;
    iPadress_ = other.iPadress_;
    timestamp_ = other.timestamp_;
    deviceType_ = other.deviceType_;
    deviceCategory_ = other.deviceCategory_;
    value_ = other.value_;
    unit_ = other.unit_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public IotUnit Clone() {
    return new IotUnit(this);
  }

  /// <summary>Field number for the "DeviceID" field.</summary>
  public const int DeviceIDFieldNumber = 1;
  private string deviceID_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string DeviceID {
    get { return deviceID_; }
    set {
      deviceID_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "IPadress" field.</summary>
  public const int IPadressFieldNumber = 2;
  private string iPadress_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string IPadress {
    get { return iPadress_; }
    set {
      iPadress_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "Timestamp" field.</summary>
  public const int TimestampFieldNumber = 3;
  private long timestamp_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public long Timestamp {
    get { return timestamp_; }
    set {
      timestamp_ = value;
    }
  }

  /// <summary>Field number for the "DeviceType" field.</summary>
  public const int DeviceTypeFieldNumber = 4;
  private string deviceType_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string DeviceType {
    get { return deviceType_; }
    set {
      deviceType_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "DeviceCategory" field.</summary>
  public const int DeviceCategoryFieldNumber = 5;
  private string deviceCategory_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string DeviceCategory {
    get { return deviceCategory_; }
    set {
      deviceCategory_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "Value" field.</summary>
  public const int ValueFieldNumber = 6;
  private double value_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public double Value {
    get { return value_; }
    set {
      value_ = value;
    }
  }

  /// <summary>Field number for the "Unit" field.</summary>
  public const int UnitFieldNumber = 7;
  private string unit_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string Unit {
    get { return unit_; }
    set {
      unit_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override bool Equals(object other) {
    return Equals(other as IotUnit);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool Equals(IotUnit other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (DeviceID != other.DeviceID) return false;
    if (IPadress != other.IPadress) return false;
    if (Timestamp != other.Timestamp) return false;
    if (DeviceType != other.DeviceType) return false;
    if (DeviceCategory != other.DeviceCategory) return false;
    if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(Value, other.Value)) return false;
    if (Unit != other.Unit) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override int GetHashCode() {
    int hash = 1;
    if (DeviceID.Length != 0) hash ^= DeviceID.GetHashCode();
    if (IPadress.Length != 0) hash ^= IPadress.GetHashCode();
    if (Timestamp != 0L) hash ^= Timestamp.GetHashCode();
    if (DeviceType.Length != 0) hash ^= DeviceType.GetHashCode();
    if (DeviceCategory.Length != 0) hash ^= DeviceCategory.GetHashCode();
    if (Value != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(Value);
    if (Unit.Length != 0) hash ^= Unit.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (DeviceID.Length != 0) {
      output.WriteRawTag(10);
      output.WriteString(DeviceID);
    }
    if (IPadress.Length != 0) {
      output.WriteRawTag(18);
      output.WriteString(IPadress);
    }
    if (Timestamp != 0L) {
      output.WriteRawTag(24);
      output.WriteInt64(Timestamp);
    }
    if (DeviceType.Length != 0) {
      output.WriteRawTag(34);
      output.WriteString(DeviceType);
    }
    if (DeviceCategory.Length != 0) {
      output.WriteRawTag(42);
      output.WriteString(DeviceCategory);
    }
    if (Value != 0D) {
      output.WriteRawTag(49);
      output.WriteDouble(Value);
    }
    if (Unit.Length != 0) {
      output.WriteRawTag(58);
      output.WriteString(Unit);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (DeviceID.Length != 0) {
      output.WriteRawTag(10);
      output.WriteString(DeviceID);
    }
    if (IPadress.Length != 0) {
      output.WriteRawTag(18);
      output.WriteString(IPadress);
    }
    if (Timestamp != 0L) {
      output.WriteRawTag(24);
      output.WriteInt64(Timestamp);
    }
    if (DeviceType.Length != 0) {
      output.WriteRawTag(34);
      output.WriteString(DeviceType);
    }
    if (DeviceCategory.Length != 0) {
      output.WriteRawTag(42);
      output.WriteString(DeviceCategory);
    }
    if (Value != 0D) {
      output.WriteRawTag(49);
      output.WriteDouble(Value);
    }
    if (Unit.Length != 0) {
      output.WriteRawTag(58);
      output.WriteString(Unit);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int CalculateSize() {
    int size = 0;
    if (DeviceID.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(DeviceID);
    }
    if (IPadress.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(IPadress);
    }
    if (Timestamp != 0L) {
      size += 1 + pb::CodedOutputStream.ComputeInt64Size(Timestamp);
    }
    if (DeviceType.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(DeviceType);
    }
    if (DeviceCategory.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(DeviceCategory);
    }
    if (Value != 0D) {
      size += 1 + 8;
    }
    if (Unit.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Unit);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(IotUnit other) {
    if (other == null) {
      return;
    }
    if (other.DeviceID.Length != 0) {
      DeviceID = other.DeviceID;
    }
    if (other.IPadress.Length != 0) {
      IPadress = other.IPadress;
    }
    if (other.Timestamp != 0L) {
      Timestamp = other.Timestamp;
    }
    if (other.DeviceType.Length != 0) {
      DeviceType = other.DeviceType;
    }
    if (other.DeviceCategory.Length != 0) {
      DeviceCategory = other.DeviceCategory;
    }
    if (other.Value != 0D) {
      Value = other.Value;
    }
    if (other.Unit.Length != 0) {
      Unit = other.Unit;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          DeviceID = input.ReadString();
          break;
        }
        case 18: {
          IPadress = input.ReadString();
          break;
        }
        case 24: {
          Timestamp = input.ReadInt64();
          break;
        }
        case 34: {
          DeviceType = input.ReadString();
          break;
        }
        case 42: {
          DeviceCategory = input.ReadString();
          break;
        }
        case 49: {
          Value = input.ReadDouble();
          break;
        }
        case 58: {
          Unit = input.ReadString();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 10: {
          DeviceID = input.ReadString();
          break;
        }
        case 18: {
          IPadress = input.ReadString();
          break;
        }
        case 24: {
          Timestamp = input.ReadInt64();
          break;
        }
        case 34: {
          DeviceType = input.ReadString();
          break;
        }
        case 42: {
          DeviceCategory = input.ReadString();
          break;
        }
        case 49: {
          Value = input.ReadDouble();
          break;
        }
        case 58: {
          Unit = input.ReadString();
          break;
        }
      }
    }
  }
  #endif

}

#endregion


#endregion Designer generated code
